# coding: utf-8

"""
    AEMET OpenData

    AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.red_rayos_api import RedRayosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRedRayosApi(unittest.TestCase):
    """RedRayosApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.red_rayos_api.RedRayosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mapa_con_los_rayos_registrados_en_periodo_standard__ltimo_elaborado_(self):
        """Test case for mapa_con_los_rayos_registrados_en_periodo_standard__ltimo_elaborado_

        Mapa con los rayos registrados en periodo standard. Último elaborado.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
