# coding: utf-8

"""
    AEMET OpenData

    AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.red_radares_api import RedRadaresApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRedRadaresApi(unittest.TestCase):
    """RedRadaresApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.red_radares_api.RedRadaresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_imagen_composicin_nacional_radares__tiempo_actual_estndar_(self):
        """Test case for imagen_composicin_nacional_radares__tiempo_actual_estndar_

        Imagen composición nacional radares. Tiempo actual estándar.  # noqa: E501
        """
        pass

    def test_radar_regional(self):
        """Test case for radar_regional

        Imagen gráfica radar regional. Tiempo actual estándar.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
