# coding: utf-8

"""
    AEMET OpenData

    AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.valores_climatologicos_api import ValoresClimatologicosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestValoresClimatologicosApi(unittest.TestCase):
    """ValoresClimatologicosApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.valores_climatologicos_api.ValoresClimatologicosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_climatologas_diarias_(self):
        """Test case for climatologas_diarias_

        Climatologías diarias.  # noqa: E501
        """
        pass

    def test_climatologas_diarias_1(self):
        """Test case for climatologas_diarias_1

        Climatologías diarias.  # noqa: E501
        """
        pass

    def test_climatologas_mensuales_anuales_(self):
        """Test case for climatologas_mensuales_anuales_

        Climatologías mensuales anuales.  # noqa: E501
        """
        pass

    def test_climatologas_normales__19812010_(self):
        """Test case for climatologas_normales__19812010_

        Climatologías normales (1981-2010).  # noqa: E501
        """
        pass

    def test_estaciones_por_indicativo_(self):
        """Test case for estaciones_por_indicativo_

        Estaciones por indicativo.  # noqa: E501
        """
        pass

    def test_inventario_de_estaciones__valores_climatolgicos_(self):
        """Test case for inventario_de_estaciones__valores_climatolgicos_

        Inventario de estaciones (valores climatológicos).  # noqa: E501
        """
        pass

    def test_valores_extremos_(self):
        """Test case for valores_extremos_

        Valores extremos.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
