# coding: utf-8

"""
    AEMET OpenData

    AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.redes_especiales_api import RedesEspecialesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRedesEspecialesApi(unittest.TestCase):
    """RedesEspecialesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.redes_especiales_api.RedesEspecialesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contenido_total_de_ozono__tiempo_actual_(self):
        """Test case for contenido_total_de_ozono__tiempo_actual_

        Contenido total de ozono. Tiempo actual.  # noqa: E501
        """
        pass

    def test_datos_de_contaminacin_de_fondo__tiempo_actual_(self):
        """Test case for datos_de_contaminacin_de_fondo__tiempo_actual_

        Datos de contaminación de fondo. Tiempo actual.  # noqa: E501
        """
        pass

    def test_datos_de_radiacin_global_directa_o_difusa__tiempo_actual_(self):
        """Test case for datos_de_radiacin_global_directa_o_difusa__tiempo_actual_

        Datos de radiación global, directa o difusa. Tiempo actual.  # noqa: E501
        """
        pass

    def test_perfiles_verticales_de_ozono__tiempo_actual_(self):
        """Test case for perfiles_verticales_de_ozono__tiempo_actual_

        Perfiles verticales de ozono. Tiempo actual.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
