# coding: utf-8

"""
    AEMET OpenData

    AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.predicciones_normalizadas_texto_api import PrediccionesNormalizadasTextoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPrediccionesNormalizadasTextoApi(unittest.TestCase):
    """PrediccionesNormalizadasTextoApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.predicciones_normalizadas_texto_api.PrediccionesNormalizadasTextoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_prediccin_ccaa_hoy__archivo_(self):
        """Test case for prediccin_ccaa_hoy__archivo_

        Predicción CCAA hoy. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_ccaa_hoy__tiempo_actual_(self):
        """Test case for prediccin_ccaa_hoy__tiempo_actual_

        Predicción CCAA hoy. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_ccaa_maana__archivo_(self):
        """Test case for prediccin_ccaa_maana__archivo_

        Predicción CCAA mañana. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_ccaa_maana__tiempo_actual_(self):
        """Test case for prediccin_ccaa_maana__tiempo_actual_

        Predicción CCAA mañana. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_ccaa_medio_plazo__archivo_(self):
        """Test case for prediccin_ccaa_medio_plazo__archivo_

        Predicción CCAA medio plazo. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_ccaa_medio_plazo__tiempo_actual_(self):
        """Test case for prediccin_ccaa_medio_plazo__tiempo_actual_

        Predicción CCAA medio plazo. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_ccaa_pasado_maana__archivo_(self):
        """Test case for prediccin_ccaa_pasado_maana__archivo_

        Predicción CCAA pasado mañana. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_ccaa_pasado_maana__tiempo_actual_(self):
        """Test case for prediccin_ccaa_pasado_maana__tiempo_actual_

        Predicción CCAA pasado mañana. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_hoy__archivo_(self):
        """Test case for prediccin_nacional_hoy__archivo_

        Predicción nacional hoy. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_hoy__tiempo_actual_(self):
        """Test case for prediccin_nacional_hoy__tiempo_actual_

        Predicción nacional hoy. Última elaborada.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_maana__archivo_(self):
        """Test case for prediccin_nacional_maana__archivo_

        Predicción nacional mañana. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_maana__tiempo_actual_(self):
        """Test case for prediccin_nacional_maana__tiempo_actual_

        Predicción nacional mañana. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_medio_plazo__archivo_(self):
        """Test case for prediccin_nacional_medio_plazo__archivo_

        Predicción nacional medio plazo. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_medio_plazo__tiempo_actual_(self):
        """Test case for prediccin_nacional_medio_plazo__tiempo_actual_

        Predicción nacional medio plazo. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_pasado_maana__archivo_(self):
        """Test case for prediccin_nacional_pasado_maana__archivo_

        Predicción nacional pasado mañana. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_pasado_maana__tiempo_actual_(self):
        """Test case for prediccin_nacional_pasado_maana__tiempo_actual_

        Predicción nacional pasado mañana. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_tendencia__archivo_(self):
        """Test case for prediccin_nacional_tendencia__archivo_

        Predicción nacional tendencia. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_nacional_tendencia__tiempo_actual_(self):
        """Test case for prediccin_nacional_tendencia__tiempo_actual_

        Predicción nacional tendencia. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_provincia_hoy__archivo_(self):
        """Test case for prediccin_provincia_hoy__archivo_

        Predicción provincia hoy. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_provincia_hoy__tiempo_actual_(self):
        """Test case for prediccin_provincia_hoy__tiempo_actual_

        Predicción provincia hoy. Tiempo actual.  # noqa: E501
        """
        pass

    def test_prediccin_provincia_maana__archivo_(self):
        """Test case for prediccin_provincia_maana__archivo_

        Predicción provincia mañana. Archivo.  # noqa: E501
        """
        pass

    def test_prediccin_provincia_maana__tiempo_actual_(self):
        """Test case for prediccin_provincia_maana__tiempo_actual_

        Predicción provincia mañana. Tiempo actual.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
