# coding: utf-8

"""
    AEMET OpenData

    AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.observacion_convencional_api import ObservacionConvencionalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestObservacionConvencionalApi(unittest.TestCase):
    """ObservacionConvencionalApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.observacion_convencional_api.ObservacionConvencionalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_datos_de_observacin__tiempo_actual_(self):
        """Test case for datos_de_observacin__tiempo_actual_

        Datos de observación. Tiempo actual.  # noqa: E501
        """
        pass

    def test_datos_de_observacin__tiempo_actual_1(self):
        """Test case for datos_de_observacin__tiempo_actual_1

        Datos de observación. Tiempo actual.  # noqa: E501
        """
        pass

    def test_mensajes_de_observacin__ltimo_elaborado_(self):
        """Test case for mensajes_de_observacin__ltimo_elaborado_

        Mensajes de observación. Último elaborado.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
